// OWNER: META agent. Trimmed real Steam store appdetails responses (l=brazilian, cc=br), captured 2026-09.
namespace GamesHub.Tests
{
    public static class MetadataFixtures
    {
        public const string CounterStrike2 = @"{""730"": {""success"": true, ""data"": {""type"": ""game"", ""name"": ""Counter-Strike 2"", ""steam_appid"": 730, ""is_free"": true, ""short_description"": ""Há mais de duas décadas, o Counter-Strike oferece uma experiência competitiva de elite moldada por milhões de jogadores mundialmente. Agora, o próximo capítulo da história do CS vai começar. Isso é Counter-Strike 2."", ""website"": ""http://counter-strike.net/"", ""developers"": [""Valve""], ""publishers"": [""Valve""], ""categories"": [{""id"": 1, ""description"": ""Multijogador""}, {""id"": 27, ""description"": ""Multijogador multiplataforma""}, {""id"": 29, ""description"": ""Cartas Colecionáveis Steam""}, {""id"": 51, ""description"": ""Oficina Steam""}, {""id"": 30, ""description"": ""Oficina Steam""}, {""id"": 35, ""description"": ""Compras em aplicativo""}, {""id"": 64, ""description"": ""Texto de tamanho ajustável""}, {""id"": 67, ""description"": ""Conforto de câmera""}, {""id"": 66, ""description"": ""Alternativas de cores""}, {""id"": 68, ""description"": ""Controles de volume independentes""}, {""id"": 74, ""description"": ""Jogável sem precisar de reação rápida""}, {""id"": 69, ""description"": ""Som estéreo""}, {""id"": 70, ""description"": ""Som surround""}, {""id"": 8, ""description"": ""Usa Valve Antitrapaça""}, {""id"": 15, ""description"": ""Estatísticas""}, {""id"": 41, ""description"": ""Remote Play no celular""}, {""id"": 42, ""description"": ""Remote Play no tablet""}, {""id"": 43, ""description"": ""Remote Play na TV""}, {""id"": 63, ""description"": ""Linha do Tempo do Steam""}], ""genres"": [{""id"": ""1"", ""description"": ""Ação""}, {""id"": ""37"", ""description"": ""Gratuitos para Jogar""}], ""release_date"": {""coming_soon"": false, ""date"": ""21/ago./2012""}}}}";

        public const string LethalCompany = @"{""1966720"": {""success"": true, ""data"": {""type"": ""game"", ""name"": ""Lethal Company"", ""steam_appid"": 1966720, ""is_free"": false, ""short_description"": ""A co-op horror about scavenging at abandoned moons to sell scrap to the Company."", ""website"": null, ""developers"": [""Zeekerss""], ""publishers"": [""Zeekerss""], ""categories"": [{""id"": 2, ""description"": ""Um jogador""}, {""id"": 1, ""description"": ""Multijogador""}, {""id"": 9, ""description"": ""Cooperativo""}, {""id"": 38, ""description"": ""Cooperativo on-line""}, {""id"": 68, ""description"": ""Controles de volume independentes""}, {""id"": 69, ""description"": ""Som estéreo""}, {""id"": 18, ""description"": ""Compat. parcial com controle""}, {""id"": 62, ""description"": ""Compartilhamento em família""}], ""genres"": [{""id"": ""1"", ""description"": ""Ação""}, {""id"": ""25"", ""description"": ""Aventura""}, {""id"": ""23"", ""description"": ""Indie""}, {""id"": ""70"", ""description"": ""Acesso Antecipado""}], ""release_date"": {""coming_soon"": false, ""date"": ""23/out./2023""}}}}";

        public const string Tekken7 = @"{""389730"": {""success"": true, ""data"": {""type"": ""game"", ""name"": ""TEKKEN 7"", ""steam_appid"": 389730, ""is_free"": false, ""controller_support"": ""full"", ""short_description"": ""AS MELHORES LUTAS SÃO AS PESSOAIS Cerre os punhos e se prepare para o combate definitivo. Desenvolvida no Unreal Engine 4, a franquia de luta está de volta para mais um round com TEKKEN 7."", ""website"": ""https://www.bandainamcostudios.com"", ""developers"": [""BANDAI NAMCO Studios Inc.""], ""publishers"": [""BANDAI NAMCO Entertainment""], ""metacritic"": {""score"": 82, ""url"": ""https://www.metacritic.com/game/pc/tekken-7""}, ""categories"": [{""id"": 2, ""description"": ""Um jogador""}, {""id"": 1, ""description"": ""Multijogador""}, {""id"": 49, ""description"": ""JxJ""}, {""id"": 36, ""description"": ""JxJ on-line""}, {""id"": 37, ""description"": ""JxJ tela dividida/compart.""}, {""id"": 24, ""description"": ""Tela dividida/compartilhada""}, {""id"": 22, ""description"": ""Conquistas Steam""}, {""id"": 28, ""description"": ""Compat. total com controle""}, {""id"": 29, ""description"": ""Cartas Colecionáveis Steam""}, {""id"": 23, ""description"": ""Nuvem Steam""}, {""id"": 25, ""description"": ""Classificações Steam""}, {""id"": 43, ""description"": ""Remote Play na TV""}, {""id"": 44, ""description"": ""Remote Play Together""}, {""id"": 62, ""description"": ""Compartilhamento em família""}], ""genres"": [{""id"": ""1"", ""description"": ""Ação""}, {""id"": ""18"", ""description"": ""Esportes""}], ""release_date"": {""coming_soon"": false, ""date"": ""1/jun./2017""}}}}";

        public const string NotFound = @"{""1"":{""success"":false}}";
    }
}
