// Generated by tools/New-UpdateSigningKey.ps1; do not edit by hand.
// Public half of the ECDSA P-256 key that signs update manifests (GamesHub-Setup-X.Y.Z.exe.sha256.sig). The private
// half exists only in the maintainer's .local folder and in the GAMESHUB_UPDATE_SIGNING_KEY release secret.
using System.Security.Cryptography;

namespace GamesHub
{
    public static class UpdateSigningKey
    {
        /// <summary>First 8 bytes of SHA-256(SubjectPublicKeyInfo), for logs.</summary>
        public const string KeyId = "f36017b8cdd6529f";
        public const string X = "1DIF3OU0kMIiryknMEJThehSPsyl2bFNL1Syje4JjXg=";
        public const string Y = "no7kLbYaBiZZ48AEI2xYC2fDe+hiarfAh5YAoLbz2/w=";

        public static ECParameters Parameters => UpdateVerifier.PublicKey(X, Y);
    }
}
