#Requires -Version 7
<#
.SYNOPSIS
  Creates the ECDSA P-256 key pair that signs GamesHub updates, or re-exports the public half of an existing key.

  - Private key: PKCS#8, Base64 on a single line, written to <main checkout>/.local/update-signing.key (git-ignored,
    readable only by the current user). It is NEVER printed. Store it as the GAMESHUB_UPDATE_SIGNING_KEY secret:
        Get-Content .local/update-signing.key -Raw | gh secret set GAMESHUB_UPDATE_SIGNING_KEY --env release
  - Public key: written to src/GamesHub/Update/UpdateSigningKey.cs. The app embeds it and refuses to run an update
    whose checksum manifest is not signed by the matching private key (see SECURITY.md).

.EXAMPLE
  pwsh tools/New-UpdateSigningKey.ps1                    # new key pair (re-exports the public key if one exists)
  pwsh tools/New-UpdateSigningKey.ps1 -Rotate            # replaces the key (lost/leaked key only): installed apps
                                                         # trust only the old key and need one manual update
  pwsh tools/New-UpdateSigningKey.ps1 -KeyFile D:\k.key  # uses/creates a key somewhere else
#>
param(
    [string]$KeyFile,
    [string]$PublicKeyFile,
    [switch]$Rotate
)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
if (-not $PublicKeyFile) { $PublicKeyFile = Join-Path $root 'src/GamesHub/Update/UpdateSigningKey.cs' }

if (-not $KeyFile) {
    # The main checkout's .local folder (linked worktrees share its .git), never inside a disposable worktree.
    $common = git -C $root rev-parse --path-format=absolute --git-common-dir 2>$null
    if ($LASTEXITCODE -ne 0 -or -not $common) { throw 'Not a git checkout: pass -KeyFile.' }
    $KeyFile = Join-Path (Split-Path $common -Parent) '.local' 'update-signing.key'
}
$KeyFile = [IO.Path]::GetFullPath($KeyFile)
$keyDir = Split-Path $KeyFile -Parent
New-Item -ItemType Directory -Force $keyDir | Out-Null

# Refuse any location git could pick up.
git -C $keyDir rev-parse --is-inside-work-tree *> $null
if ($LASTEXITCODE -eq 0) {
    git -C $keyDir check-ignore -q -- $KeyFile
    if ($LASTEXITCODE -ne 0) { throw "Refusing to write the private key to a path git does not ignore: $KeyFile" }
}

$ecdsa = [Security.Cryptography.ECDsa]::Create([Security.Cryptography.ECCurve+NamedCurves]::nistP256)
try {
    if ((Test-Path $KeyFile) -and -not $Rotate) {
        $read = 0
        $ecdsa.ImportPkcs8PrivateKey([Convert]::FromBase64String((Get-Content $KeyFile -Raw).Trim()), [ref]$read)
        if ($ecdsa.KeySize -ne 256) { throw "Existing key is not ECDSA P-256: $KeyFile" }
        Write-Host "Using the existing private key: $KeyFile"
    } else {
        # Create the file and lock it to the current user before any key material is written.
        Set-Content -LiteralPath $KeyFile -Value '' -NoNewline
        if ($IsWindows) {
            icacls $KeyFile /inheritance:r /grant:r "$([Security.Principal.WindowsIdentity]::GetCurrent().Name):(F)" | Out-Null
            if ($LASTEXITCODE -ne 0) { Write-Warning 'Could not restrict the key file ACL (icacls failed).' }
        }
        [IO.File]::WriteAllText($KeyFile, [Convert]::ToBase64String($ecdsa.ExportPkcs8PrivateKey()), [Text.UTF8Encoding]::new($false))
        Write-Host "New private key written to $KeyFile (not shown)." -ForegroundColor Green
    }

    $q = $ecdsa.ExportParameters($false).Q
    $x = [Convert]::ToBase64String($q.X)
    $y = [Convert]::ToBase64String($q.Y)
    $spki = $ecdsa.ExportSubjectPublicKeyInfo()
    $keyId = -join ([Security.Cryptography.SHA256]::HashData($spki)[0..7] | ForEach-Object { $_.ToString('x2') })
} finally { $ecdsa.Dispose() }

$cs = @"
// Generated by tools/New-UpdateSigningKey.ps1; do not edit by hand.
// Public half of the ECDSA P-256 key that signs update manifests (GamesHub-Setup-X.Y.Z.exe.sha256.sig). The private
// half exists only in the maintainer's .local folder and in the GAMESHUB_UPDATE_SIGNING_KEY release secret.
using System.Security.Cryptography;

namespace GamesHub
{
    public static class UpdateSigningKey
    {
        /// <summary>First 8 bytes of SHA-256(SubjectPublicKeyInfo), for logs.</summary>
        public const string KeyId = "$keyId";
        public const string X = "$x";
        public const string Y = "$y";

        public static ECParameters Parameters => UpdateVerifier.PublicKey(X, Y);
    }
}

"@
[IO.File]::WriteAllText($PublicKeyFile, ($cs -replace "`r`n", "`n"), [Text.UTF8Encoding]::new($false))
Write-Host "Public key $keyId written to $PublicKeyFile"
Write-Host 'Next: store the private key as the GAMESHUB_UPDATE_SIGNING_KEY secret (see docs/PIPELINE.md).'
